### PR TITLE
Add xcodeproj for Carthage support

### PR DESCRIPTION
**Pull request by avriy**

### CODE REVIEW

**Comment by JohnSundell** [comment]
Hey @avriy 👋 Thanks for this contribution. I'm not very keen on adding an Xcode project to this repo, since it adopts the Swift Package Manager workflow with a git ignored Xcode project that gets ad-hoc generated whenever you need it. This makes the file system the source of truth, which is super nice. That being said, I'd love to be able to support Carthage. Is there a way to add a custom build step to Carthage that would generate the Xcode project using `swift package generate-xcodeproj`?

**Comment by avriy** [comment]
Yes, you are right, there is support in Carthage for building SwiftPM(I was not aware of it), you just do `carthage bootstrap --platform macOS`

**Comment by JohnSundell** [comment]
@avriy Ah, perfect 👍

**Comment by avriy** [comment]
I was misled by --cache-builds that was taking the wrong version. So, there is no support in the Carthage for SwiftPM yet 
https://github.com/Carthage/Carthage/issues/1559

**Pull request closed without merging**
