### PR TITLE
Use default rawValue for String

### PR DESCRIPTION
**Pull request by pixyzehn**
I think it's better to use default rawValue in this case. What do you think?

### CODE REVIEW

**Comment by JohnSundell** [comment]
What does this change accomplish? 😇

**Comment by pixyzehn** [comment]
There is no accomplishment, but you can omit these string name.
If you have an intention for that, I'll close :)

**Comment by JohnSundell** [comment]
Yeah, the intention is to have easier argument parsing in command line tools, by only having lower cased names 🙂

**Comment by pixyzehn** [comment]
Sorry, it's my fault, I thought `rawValue` will be lower cased names automatically. 
Thank you for making me notice.

**Pull request closed without merging**
