### PR TITLE
Add Package.pins in gitignore

### PR DESCRIPTION
**Pull request by pixyzehn**
Ignored `Package.pins`.

### CODE REVIEW

**Comment by JohnSundell** [comment]
Why not check in the pins? (This is the default for `swift package init`)

**Comment by pixyzehn** [comment]
The problem is that we should use same (SSH or HTTPS) repositoryURL in `Package.swift` and `Package.pins`.
If I execute `swift package update`, pins changes like this because of using SSH in `Package.swift`.

```
     {
       "package": "Files",
       "reason": null,
-      "repositoryURL": "https://github.com/johnsundell/files.git",
+      "repositoryURL": "git@github.com:johnsundell/files.git",
       "version": "1.6.2"
     }
   ],
```

So I referred to https://github.com/JohnSundell/Marathon/blob/master/.gitignore#L40. If you don't want to be placed in the .gitignore file, could you update pins to use SSH?

**Comment by JohnSundell** [comment]
@pixyzehn Good point, let's git ignore then! 👍

**Comment by pixyzehn** [comment]
Thanks as usual :)

**Pull request merged**
